const products = [
  {
    name: '듀얼픽스 i-SIZE',
    company: '브라이텍스',
    country: '독일',
    price: 1125000,
    minAge: 0,
    maxAge: 60,
    group: ['신생아', '유아'],
    tags: ['ISOFIX', 'i-SIZE', '회전형', '앞뒤보기'],
  },
  {
    name: '듀얼픽스2',
    company: '브라이텍스',
    country: '독일',
    price: 795000,
    minAge: 0,
    maxAge: 60,
    group: ['신생아', '유아'],
    tags: ['ISOFIX', '회전형', '앞뒤보기'],
  },
  {
    name: '어드밴스픽스4',
    company: '브라이텍스',
    country: '독일',
    price: 725000,
    minAge: 9,
    maxAge: 144,
    group: ['유아', '주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '롬머키드픽스3',
    company: '브라이텍스',
    country: '독일',
    price: 635000,
    minAge: 36,
    maxAge: 144,
    group: ['주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '롬머키드픽스 SL SICT',
    company: '브라이텍스',
    country: '독일',
    price: 480000,
    minAge: 36,
    maxAge: 144,
    group: ['주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '밀레니아',
    company: '브라이텍스',
    country: '호주',
    price: 960000,
    minAge: 0,
    maxAge: 60,
    group: ['신생아', '유아'],
    tags: ['ISOFIX', '앞뒤보기'],
  },
  {
    name: '메디리안3',
    company: '브라이텍스',
    country: '호주',
    price: 750000,
    minAge: 0,
    maxAge: 60,
    group: ['신생아', '유아'],
    tags: ['ISOFIX', '앞뒤보기'],
  },
  {
    name: '로얄2',
    company: '브라이텍스',
    country: '호주',
    price: 650000,
    minAge: 0,
    maxAge: 60,
    group: ['신생아', '유아'],
    tags: ['ISOFIX', '앞뒤보기'],
  },
  {
    name: '갤럭시3',
    company: '브라이텍스',
    country: '호주',
    price: 635000,
    minAge: 0,
    maxAge: 60,
    group: ['신생아', '유아'],
    tags: ['ISOFIX', '앞뒤보기'],
  },
  {
    name: '오메가3',
    company: '브라이텍스',
    country: '호주',
    price: 580000,
    minAge: 0,
    maxAge: 60,
    group: ['신생아', '유아'],
    tags: ['ISOFIX', '앞뒤보기'],
  },
  {
    name: '맥시플러스2',
    company: '브라이텍스',
    country: '호주',
    price: 550000,
    minAge: 9,
    maxAge: 96,
    group: ['유아', '주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '어드보케이트',
    company: '브라이텍스',
    country: '미국',
    price: 765000,
    minAge: 0,
    maxAge: 96,
    group: ['신생아', '유아', '주니어'],
    tags: ['ISOFIX', '앞뒤보기'],
  },
  {
    name: '하이포인트',
    company: '브라이텍스',
    country: '미국',
    price: 315000,
    minAge: 36,
    maxAge: 96,
    group: ['주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '제로원',
    company: '레카로',
    country: '독일',
    price: 850000,
    minAge: 0,
    maxAge: 36,
    group: ['신생아', '유아'],
    tags: ['ISOFIX', 'i-SIZE', '회전형', '앞뒤보기'],
  },
  {
    name: '영스포트 히어로',
    company: '레카로',
    country: '독일',
    price: 650000,
    minAge: 9,
    maxAge: 108,
    group: ['유아', '주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '몬자노바EVO',
    company: '레카로',
    country: '독일',
    price: 380000,
    minAge: 36,
    maxAge: 132,
    group: ['주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '몬자노바SF',
    company: '레카로',
    country: '독일',
    price: 418000,
    minAge: 36,
    maxAge: 132,
    group: ['주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '제로나 Q i-SIZE 플러스',
    company: '싸이벡스',
    country: '독일',
    price: 1090000,
    minAge: 0,
    maxAge: 60,
    group: ['신생아', '유아'],
    tags: ['ISOFIX', 'i-SIZE', '회전형', '앞뒤보기'],
  },
  {
    name: '제로나 플러스',
    company: '싸이벡스',
    country: '독일',
    price: 990000,
    minAge: 0,
    maxAge: 60,
    group: ['신생아', '유아'],
    tags: ['ISOFIX', '회전형', '앞뒤보기'],
  },
  {
    name: '솔루션 Z-FIX 플러스',
    company: '싸이벡스',
    country: '독일',
    price: 580000,
    minAge: 36,
    maxAge: 144,
    group: ['주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '솔루션 Z-FIX',
    company: '싸이벡스',
    country: '독일',
    price: 430000,
    minAge: 36,
    maxAge: 144,
    group: ['주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '솔루션 Q2-FIX 플러스',
    company: '싸이벡스',
    country: '독일',
    price: 580000,
    minAge: 36,
    maxAge: 144,
    group: ['주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '트랜스포머 테크',
    company: '콩코드',
    country: '독일',
    price: 249000,
    minAge: 36,
    maxAge: 144,
    group: ['주니어'],
    tags: ['ISOFIX'],
  },
  {
    name: '트랜스포머 XT 플러스',
    company: '콩코드',
    country: '독일',
    price: 420000,
    minAge: 36,
    maxAge: 144,
    group: ['주니어'],
    tags: ['ISOFIX'],
  },
];

export default products;
